#!/bin/sh

set -o nounset \
    -o errexit \
    -o verbose \
    -o xtrace


# Set environment values if they exist as arguments
if [ $# -ne 0 ]; then
  echo "===> Overriding env params with args ..."
  for var in "$@"
  do
    export "$var"
  done
fi

echo "===> ENV Variables ..."
env | sort

echo "===> User"
id

echo "===> Waiting for database ..."
/bin/sh ./wait-for "${TAX_RATES_DB_HOST}:${TAX_RATES_DB_PORT}"

echo "===> Pausing for users to be created ..."
sleep 5

echo "===> Loading data ..."
python loader.py

echo "===> Running ... "
python app.py
